spring:
  mvc:
    view:
      prefix: /views/jsp/
      suffix: .jsp
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://192.168.1.4:3306/question?useUnicode=true&characterEncoding=GBK&useSSL=false&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 10088





